### ISSUE TITLE
problem installing new radiusdesk script with ansible

### ISSUE THREAD

**Issue by j0r1993** [muffycompo/radiusdesk-installer#18] opened 2016-02-26 17:32 UTC
Hi.. im trying to installing the new script that you have published... 
i want to install in localhost, i put in ssh "ssh localhost" i write yes and i put the password..
but when i try to install he show me this error

http://prntscr.com/a89882

**Comment by muffycompo** [comment] 2016-02-26 17:54
What user are you using to run the installer, is it the root user or a regular user? The installer assumes you are running as root, there is a patch that will be pushed within the weekend but until then, make sure you are logged in as the root user on your control machine/host

**Comment by j0r1993** [comment] 2016-02-26 17:55
im using root

**Comment by muffycompo** [comment] 2016-02-26 17:59
Right now, I am trying to recreate the problem but it seem to be working fine. Just an aside, do you have Python 2.7+ installed?

**Comment by j0r1993** [comment] 2016-02-26 18:00
Python 2.7.6

**Comment by muffycompo** [comment] 2016-02-26 20:31
@j0r1993 I have push a fix for this issue after I finally reproduced the bug. You can clone a fresh copy of the installer or just edit your `servers` file and ensure the following change: 
```
[default]
localhost
```

Becomes:

```
[default]
localhost ansible_connection=local ansible_ssh_user=root
```

**Comment by j0r1993** [comment] 2016-02-26 20:37
now work.. but there is 1 error i show you

http://prntscr.com/a8c6rb

**Comment by muffycompo** [comment] 2016-02-26 20:49
Can you try updating your Ansible version from 1.5.x to the recent one? Follow this [guide](http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-apt-ubuntu) and after installing the updated Ansible, run this the installer again and get back to us.

**Comment by j0r1993** [comment] 2016-02-26 20:53
updated but same error..

**Comment by j0r1993** [comment] 2016-02-26 20:56
there isn't no radiusdesk folder installed 

http://prntscr.com/a8chb2

**Comment by muffycompo** [comment] 2016-02-26 21:01
Looks like the installation did not complete that's why. Are you still getting the error after the update of Ansible?

**Comment by j0r1993** [comment] 2016-02-26 21:02
yes

TASK [radiusdesk : Downloading RadiusDesk CakePHP Source from Subversion (Ubuntu)] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'int' object has no attribute 'startswith'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "parsed": false}

**Comment by muffycompo** [comment] 2016-02-26 22:02
I have created a new bugfix branch and kindly test and revert back.

To checkout the bugfix branch, just do the following:

`git checkout -b bugfix_18 http://github.com/muffycompo/radiusdesk-installer`

**Comment by j0r1993** [comment] 2016-02-26 22:26
work!!.. all installation passed without error!! you are fantastic :D thanks for all you doing for us

**Comment by muffycompo** [comment] 2016-02-26 22:30
I am glad I could help fix it for you. I will merge the changes to the master branch to ensure others don't have the same problem and thank you too for trying it out because without your feedback, this fix will have not been implemented.

**Closed by muffycompo** 2016-02-26 22:30 UTC
Labels: bug

**Comment by iberrywifi** [comment] 2017-02-19 13:17
Dear muffy i am facing below this issue when installing on centos 7 on cloud 
TASK [radiusdesk : Downloading RadiusDesk CakePHP Source from Subversion (RHEL/C                                                                                        entOS 6+)] ***
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "svn checkout -r 1951 ht                                                                                        tp://svn.code.sf.net/p/radiusdesk/code/trunk/rd_cake /tmp/rd_sources/rd_cake", "                                                                                        delta": "0:00:00.674130", "end": "2017-02-19 07:58:07.820619", "failed": true, "                                                                                        rc": 1, "start": "2017-02-19 07:58:07.146489", "stderr": "svn: E175002: Unable t                                                                                        o connect to a repository at URL 'http://svn.code.sf.net/p/radiusdesk/code/trunk                                                                                        /rd_cake'\nsvn: E175002: OPTIONS of 'http://svn.code.sf.net/p/radiusdesk/code/tr                                                                                        unk/rd_cake': could not connect to server (http://svn.code.sf.net)", "stdout": "                                                                                        ", "stdout_lines": [], "warnings": ["Consider using subversion module rather tha                                                                                        n running svn"]}

RUNNING HANDLER [radiusdesk : Start Nginx] *************************************

RUNNING HANDLER [radiusdesk : Restart Nginx] ***********************************

RUNNING HANDLER [radiusdesk : Start PHP-FPM] ***********************************

RUNNING HANDLER [radiusdesk : Restart PHP-FPM] *********************************
        to retry, use: --limit @/root/radiusdesk-installer/rd-installer-ansible.                                                                                        retry

PLAY RECAP *********************************************************************
localhost                  : ok=14   changed=9    unreachable=0    failed=1

[root@iberrycloud radiusdesk-installer]# cd..

**Comment by muffycompo** [comment] 2017-02-20 10:00
@iberywifi, the issue is with sourceforge, I tried to reproduce the error and I had the same thing, trying it manually also yielded the same results, it times out when doing an "svn checkout" of radiusdesk trunk. Hopefully it gets fixed and the installer should work as normal.

**Comment by iberrywifi** [comment] 2017-02-20 14:53
Is there any other way to install other than from sourceforge.

On Mon, Feb 20, 2017 at 3:30 PM, Mfawa Alfred Onen <notifications@github.com
